### ISSUE TITLE
自定义更新dialog时会报强转异常

### ISSUE THREAD

**Issue by LiaoFuYun** [yjfnypeu/UpdatePlugin#16]
`java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity
at org.lzh.framework.updatepluginlib.util.SafeDialogOper.safeShowDialog(SafeDialogOper.java:23)
at org.lzh.framework.updatepluginlib.callback.DefaultCheckCB.hasUpdate(DefaultCheckCB.java:60)
at org.lzh.framework.updatepluginlib.business.UpdateWorker$1.run(UpdateWorker.java:96)`
创建dialog时的context我都试过了，都会出现这个错误

**Comment by yjfnypeu** [comment]
你的怎样使用的呢？

**Comment by LiaoFuYun** [comment]
![image](https://cloud.githubusercontent.com/assets/17230978/18239800/2940fcb4-737a-11e6-83d7-ba518b375193.png)
我在你的demo里面加了.updateDialogCreator,里面的实现也是从DefaultNeedUpdateCreator.java里面copy的

**Comment by yjfnypeu** [comment]
你加一下交流群吧。咱们详细讨论下，这种问题还没遇到过。群号是
108895031

**Comment by LiaoFuYun** [comment]
好的，非常感谢
