### ISSUE TITLE
Wifi网络下，不提示自动更新（华为noval2）

### ISSUE THREAD

**Issue by zhengweig** [yjfnypeu/UpdatePlugin#68]
Wifi网络下，不提示自动更新（华为noval2），只有切换成移动网络，才会有提示。

**Comment by zhengweig** [comment]
补充log日志：
E/UpdatePluginLog: Download task has occurs error: connect timed out
                                                                                         java.net.SocketTimeoutException: connect timed out
                                                                                             at java.net.PlainSocketImpl.socketConnect(Native Method)
                                                                                             at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
                                                                                             at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
                                                                                             at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
                                                                                             at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
                                                                                             at java.net.Socket.connect(Socket.java:592)
                                                                                             at com.android.okhttp.internal.Platform.connectSocket(Platform.java:113)
                                                                                             at com.android.okhttp.Connection.connectSocket(Connection.java:196)
                                                                                             at com.android.okhttp.Connection.connect(Connection.java:172)
                                                                                             at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
                                                                                             at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
                                                                                             at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
                                                                                             at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
                                                                                             at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
                                                                                             at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
                                                                                             at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521)
                                                                                             at org.lzh.framework.updatepluginlib.impl.DefaultDownloadWorker.supportBreakpointDownload(DefaultDownloadWorker.java:118)
                                                                                             at org.lzh.framework.updatepluginlib.impl.DefaultDownloadWorker.download(DefaultDownloadWorker.java:71)
                                                                                             at org.lzh.framework.updatepluginlib.base.DownloadWorker.run(DownloadWorker.java:75)
                                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                             at java.lang.Thread.run(Thread.java:776)

**Comment by zhengweig** [comment]
E/UpdatePluginLog: Download task has occurs error: The version code not matched between apk and update entity. apk is 90 but update is 109
                                                                                       java.lang.IllegalStateException: The version code not matched between apk and update entity. apk is 90 but update is 109
                                                                                           at org.lzh.framework.updatepluginlib.impl.DefaultFileChecker.checkByPM(DefaultFileChecker.java:59)
                                                                                           at org.lzh.framework.updatepluginlib.impl.DefaultFileChecker.check(DefaultFileChecker.java:49)
                                                                                           at org.lzh.framework.updatepluginlib.impl.DefaultFileChecker.onCheckBeforeInstall(DefaultFileChecker.java:88)
                                                                                           at org.lzh.framework.updatepluginlib.base.DownloadWorker.sendDownloadComplete(DownloadWorker.java:144)
                                                                                           at org.lzh.framework.updatepluginlib.impl.DefaultDownloadWorker.renameAndNotifyCompleted(DefaultDownloadWorker.java:140)
                                                                                           at org.lzh.framework.updatepluginlib.impl.DefaultDownloadWorker.download(DefaultDownloadWorker.java:93)
                                                                                           at org.lzh.framework.updatepluginlib.base.DownloadWorker.run(DownloadWorker.java:75)
                                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                           at java.lang.Thread.run(Thread.java:776)

**Comment by yjfnypeu** [comment]
提示已经很明显了，你接口提供的版本号与你下载的apk的版本号匹配不上，所以导致更新失败了。
接口中返回的版本号是109，而你实际apk的版本号是90.

**Comment by zhaoxiuyu** [comment]
匹配不上是什么意思，难道要版本号一样才能更新吗？
