### ISSUE TITLE
Unable to get provider: UpdateInstallProvider ClassNotFoundException

### ISSUE THREAD

**Issue by jackyHuangH** [yjfnypeu/UpdatePlugin#71]
java.lang.RuntimeException: Unable to get provider org.lzh.framework.updatepluginlib.util.UpdateInstallProvider: java.lang.ClassNotFoundException: Didn't find class "org.lzh.framework.updatepluginlib.util.UpdateInstallProvider" on path: DexPathList[[zip file "/data/app/com.zenchn.cooperationfarmhouse-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.zenchn.cooperationfarmhouse-1, /system/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:4795)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4387)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4327)
        at android.app.ActivityThread.access$1500(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5019)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by yjfnypeu** [comment]
目测可能是你们multidex分包把这个Provider分到子包中去了导致的。查查相关资料解决吧

**Comment by yjfnypeu** [comment]
你可以参考这篇的做法：[Android的multidex带来NoClassDefFoundError](https://www.jianshu.com/p/03c28e64b636)

**Comment by jackyHuangH** [comment]
感谢，已完美解决！！！
