### ISSUE TITLE
Download task has occurs error: Attempt to read from field'int‘android.content.pm.PackageInfo.versionCode' on a null object reference

### ISSUE THREAD

**Issue by swordblade17** [yjfnypeu/UpdatePlugin#72]
Download task has occurs error: Attempt to read from field'int‘android.content.pm.PackageInfo.versionCode' on a null object reference
    java.lang.NullPointerException: Attempt to read from `field` 'int android.content.pm.PackageInfo.versionCode' on a null object reference
        at org.lzh.framework.updatepluginlib.impl.DefaultFileChecker.checkByPM(DefaultFileChecker.java:57)
        at org.lzh.framework.updatepluginlib.impl.DefaultFileChecker.check(DefaultFileChecker.java:49)
        at org.lzh.framework.updatepluginlib.impl.DefaultFileChecker.onCheckBeforeInstall(DefaultFileChecker.java:88)
        at org.lzh.framework.updatepluginlib.base.DownloadWorker.sendDownloadComplete(DownloadWorker.java:144)
        at org.lzh.framework.updatepluginlib.impl.DefaultDownloadWorker.renameAndNotifyCompleted(DefaultDownloadWorker.java:140)
        at org.lzh.framework.updatepluginlib.impl.DefaultDownloadWorker.download(DefaultDownloadWorker.java:93)
        at org.lzh.framework.updatepluginlib.base.DownloadWorker.run(DownloadWorker.java:75)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:776)

**Comment by yjfnypeu** [comment]
这个我下个版本控制过滤一下，不过如果可以的话建议可以考虑使用md5的方式进行验证。就能避免此问题

**Comment by swordblade17** [comment]
了解了，谢谢
