### ISSUE TITLE
ActivityManager.ext报错

### ISSUE THREAD

**Issue by CelestialPossession** [yjfnypeu/UpdatePlugin#93]
报错的LOG

java.util.NoSuchElementException
    at java.util.LinkedList.removeFirstImpl(LinkedList.java:689)
    at java.util.LinkedList.pop(LinkedList.java:794)
    at org.lzh.framework.updatepluginlib.util.ActivityManager.exit(ActivityManager.java:98)

public void exit() {
        Activity activity;
        while ((activity = stack.pop()) != null) {
            if (!activity.isFinishing()) {
                activity.finish();
            }
        }
        System.exit(0);
        Process.killProcess(Process.myPid());
    }

while语句需要判断一下stack的大小。pop在返回之前先报错了

**Comment by LilSacred** [comment]
我发现3.1.2你提交了更改。但是android studio下载的ActivityManager仍然是上面那种写法，我在release下了源码，发现也是上面那种。请问这是为什么？
